language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest
    - WP_VERSION=3.8

before_script:
    - bash bin/install-wp-tests.sh wordpress_test travis '' localhost $WP_VERSION 

script: phpunit
